{application,prism_listener,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{prism_listener_app,[]}},
              {env,[]},
              {modules,[callback_handler,prism_listener_app,
                        prism_listener_sup]}]}.
